name: Auto-merge
on: pull_request_target
jobs:
  automerge:
    uses: open-contracting/.github/.github/workflows/automerge.yml@main
    permissions:
      actions: true
      contents: write
      pull-requests: write
